### ISSUE TITLE
Issue while installing dependencies (npm install)

### ISSUE THREAD

**Issue by yashparihar** [hirokimoto/spin#1]
Hi there,
I have keen interest in using your Spin theme for my project..
mainly "Full-Version-ReactJS" and so  i am only installing dependecies of 'Full-version-Reactjs' while ignoring other file(Full-version-html,Full-version-gulp,etc) 
 
but while installing dependencies, i am facing some issue..
(my NPM version is 5.6.0.. and NODE version v8.9.4)

What i think  this issue is due to my NPM version is higher while the dependencies mentioned in package.json is somewhat older
or
issue might be because of some other problem..

This kind of error shows up:
`
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (I:\practice\spin-react-theme\spin\Full-Version-ReactJS\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (I:\practice\spin-react-theme\spin\Full-Version-ReactJS\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at I:\practice\spin-react-theme\spin\Full-Version-ReactJS\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "I:\\practice\\spin-react-theme\\spin\\Full-Version-ReactJS\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsa
ss_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd I:\practice\spin-react-theme\spin\Full-Version-ReactJS\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN The package string-replace-loader is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yash\AppData\Roaming\npm-cache\_logs\2018-04-20T11_46_56_463Z-debug.log
`

Please help me regarding this, Thank you

**Comment by yashparihar** [comment]
hae the problem was resolved... 
Actually it was not npm version problem.

I followed this below steps and the proj successfully bultd

First I installed windows-build-tools and node-gyp: (Python should be installed globally on ur machine)
npm --add-python-to-path='true' --debug install --global windows-build-tools
npm install --global node-gyp

and turn off my antivirus scanning and firewall

and then 'npm install' ; all worked fine..

but their are still lots of warning poping up.
